model:
  output_dim: 512
  checkpoint_path: saved_models/clip_triplet.pt

data:
  gallery_dir: data/new_animals/test/gallery
  query_dir: data/new_animals/test/query

retrieval:
  top_k: 10
  output_json: results_clip_triplet.json

