model:
  name: ResNet50

dataset:
  name: DTD
  output_dim: 47
  path_root: data/dtd
  use_custom_split: false      # false = usa split ufficiale, true = fa random split
  val_split: 0.2               # usato solo se use_custom_split = true
  train_init_args:
    split: train               # usato solo se use_custom_split = false
  val_init_args:
    split: val                 # usato solo se use_custom_split = false

data:
  img_size: 224
  batch_size_train: 64
  batch_size_val: 64
  batch_size_test: 64
  num_workers: 4

training:
  num_epochs: 15
  lr_head: 1e-3
  lr_backbone: 1e-4
  save_name: saved_models/resnet_dtd.pt

pretrained:
  pre_t: true
  load: "saved_models/resnet_dtd.pt"

finetune: true

logger:
  wandb: false
