model:
  name: ResNet50

dataset:
  name: OxfordIIITPet
  output_dim: 37
  path_root: data/pets
  train_init_args:
    split: trainval
    target_types: category
  val_init_args:
    split: test
    target_types: category

data:
  batch_size_train: 64
  batch_size_test: 64
  num_workers: 4
  val_split: 0.2  # ATTENZIONE: questo applica lo split interno su trainval

training:
  num_epochs: 10
  save_name: saved_models/resnet_pets.pt

pretrained:
  pre_t: true
  load: ""

finetune: true

logger:
  wandb: false
