model:
  name: ResNet50

dataset:
  name: CIFAR10
  output_dim: 10
  path_root: data/cifar10
  train_init_args:
    train: true
  val_init_args:
    train: false

data:
  batch_size_train: 64
  batch_size_test: 64
  num_workers: 4

training:
  num_epochs: 15
  save_name: saved_models/resnet_cifar10.pt

pretrained:
  pre_t: true
  load: ""

finetune: true

logger:
  wandb: false
