model:
  name: resnet50_moco
  source: custom
  pretrained: true
  checkpoint_path: saved_models/moco_v2_200ep.pth.tar
  output_dim: 2048

data:
  train_dir: data/new_animals/train  # non serve per retrieval ma lo lasciamo
  gallery_dir: data/new_animals/test/gallery
  query_dir: data/new_animals/test/query
  img_size: 224
  batch_size: 64
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  val_split: 0.0  # non serve per retrieval

training:
  num_epochs: 0  # saltiamo il training
  freeze_backbone: true
  lr_backbone: 0.0
  lr_head: 0.0
  save_checkpoint: ""

retrieval:
  top_k: 10
  output_json: results_moco_v2.json
