model:
  name: moco_resnet50
  source: custom
  pretrained: false
  checkpoint_path: saved_models/moco_resnet50_finetuned_triplet.pt
  output_dim: 2048

data:
  train_dir: data/new_animals/train
  gallery_dir: data/new_animals/test/gallery
  query_dir: data/new_animals/test/query
  img_size: 224
  batch_size: 32
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  val_split: 0.2

training:
  num_epochs: 10
  freeze_backbone: false
  lr_backbone: 1e-5
  lr_head: 1e-3
  optimizer: adam  # puoi mettere 'adam' o 'sgd' se lo script supporta la lettura
  save_checkpoint: saved_models/moco_resnet50_finetuned_triplet.pt

retrieval:
  top_k: 10
  output_json: results_moco_resnet50_finetuned.json

