model:
  name: "openai/clip-vit-large-patch14" 
  source: "huggingface"
  checkpoint_path: #saved_models/clip_vitl14_finetuned.pt

data:
  train_dir: data/train
  query_dir: data/test/query 
  gallery_dir: data/test/gallery 
  img_size: 224 
  batch_size: 8

training:
  num_epochs: 20
  freeze_backbone: false
  lr_backbone: 1e-6 
  lr_head: 1e-4 
  save_checkpoint: saved_models/clip_vitl14_finetuned.pt

retrieval:
  top_k: 10 
  output_json: results/results_clip_vitL14.json