model:
  name: resnet50
  source: torchvision
  pretrained: true
  checkpoint_path: #competition/saved_models/resnet50_finetuned_triplet.pt
  output_dim: 2048

data:
  train_dir: #competition/data/Data_example/training
  gallery_dir: #competition/data/Data_example/test/gallery
  query_dir: #competition/data/Data_example/test/query
  img_size: 224
  batch_size: 32
  normalization:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  val_split: 0.1

training:
  num_epochs: 10
  freeze_backbone: false
  lr_backbone: 1e-5
  lr_head: 1e-3
  margin: 0.2
  save_checkpoint:  #competition/saved_models/resnet50_finetuned_triplet.pt

retrieval:
  top_k: 10
  output_json:    #competition/results_resnet50_finetued_triplet.json  