model:
  name: resnet50
  source: torchvision
  pretrained: true
  checkpoint_path: saved_models/resnet50_finetuned.pt
  output_dim: 2048

data:
  train_dir: data//train
  gallery_dir: data/test/gallery
  query_dir: data/test/query
  img_size: 224
  batch_size: 32
  val_split: 0.1

training:
  num_epochs: 10
  freeze_backbone: false
  lr_backbone: 1e-5
  lr_head: 1e-3
  margin: 0.2
  save_checkpoint: saved_models/resnet50_finetuned.pt

retrieval:
  top_k: 10
  output_json: results/results_resnet50_finetuned.json  