model:
  name: EVA01-g-14
  source: open_clip
  pretrained: laion400m_s11b_b41k
  checkpoint_path: #saved_models/eva_clip_finetuned_triplet.pt

data:
  train_dir: Animal_Image_Dataset_slpit/train
  query_dir: Animal_Image_Dataset_slpit/test/query
  gallery_dir: Animal_Image_Dataset_slpit/test/gallery
  img_size: 224
  batch_size: 8

training:
  num_epochs: 10
  freeze_backbone: false 
  lr_backbone: 1e-5
  lr_head: 1e-3
  save_checkpoint: saved_models/eva_clip_finetuned_animals.pt

retrieval:
  top_k: 10
  output_json: results/results_eva01_g14_animals.json