model:
  name: resnet50
  source: torchvision
  pretrained: true
  checkpoint_path: saved_models/resnet50_finetuned.pt
  output_dim: 2048

data:
  train_dir: Animal_Image_Dataset_slpit/train
  query_dir: Animal_Image_Dataset_slpit/test/query
  gallery_dir: Animal_Image_Dataset_slpit/test/gallery
  img_size: 224
  batch_size: 32
  val_split: 0.1

training:
  num_epochs: 10
  freeze_backbone: false
  lr_backbone: 1e-5
  lr_head: 1e-3
  save_checkpoint: saved_models/resnet50_finetuned_animals.pt

retrieval:
  top_k: 10
  output_json: results/results_resnet50_finetuned_animals.json  